import"./assets/styles-CQQbgYeD.js";import{a as n,i as c}from"./assets/vendor-ZnMw6IGI.js";const s={categoryList:document.querySelector(".categories"),productList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn"),searchForm:document.querySelector(".search-form"),searchBtnClear:document.querySelector(".search-form__btn-clear"),searchInput:document.querySelector(".search-form__input")};n.defaults.baseURL="https://dummyjson.com";async function h(){try{const{data:t}=await n("/products/categories");return t}catch(t){c.error({message:t.message,position:"topRight"})}}async function u(t){const e=`/products?limit=12&skip=${(t-1)*12}`;try{const{data:o}=await n(e);return o}catch(o){c.error({message:o.message,position:"topRight"})}}async function f(t){const e=`products/category/${t}`;try{const{data:o}=await n(e);return o}catch(o){c.error({message:o.message,position:"topRight"})}}async function L(t){const e=`products/${t}`;try{const{data:o}=await n(e);return o}catch(o){c.error({message:o.message,position:"topRight"})}}async function b(t,e=1,o=12){const r=(e-1)*12,i=`products/search?q=${encodeURIComponent(t)}&limit=${o}&skip=${r}`;try{const{data:a}=await n(i);return a}catch(a){c.error({message:a.message,position:"topRight"})}}const $=t=>t.map(({name:e})=>`<li class="categories__item">
   <button class="categories__btn" type="button">${e}</button>
 </li>
`).join(""),P=async()=>{const t=await h();t.unshift({name:"All"}),s.categoryList.insertAdjacentHTML("beforeend",$(t))},g=t=>t.map(({id:e,thumbnail:o,title:r,brand:i,category:a,price:d})=>`<li class="products__item" data-id="${e}">
    <img class="products__image" src="${o}" alt="${r}"/>
    <p class="products__title">${r}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${i}</span></p>
    <p class="products__category">Category: ${a} </p>
    <p class="products__price">Price: ${d}$</p>
 </li>

`).join(""),v=async t=>{const{products:e}=await u(t);e.length>0&&s.productList.insertAdjacentHTML("beforeend",g(e))};function l(t){s.productList.innerHTML=g(t)}function p(){s.notFound.classList.add("not-found--visible")}function m(){s.notFound.classList.remove("not-found--visible")}function C({thumbnail:t,title:e,price:o,tags:r=[],description:i,returnPolicy:a,shippingInformation:d}){const y=r.map(_=>`<li>${_}</li>`).join("");return`<img class="modal-product__img" src="${t}" alt="${e}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${e}</p>
        <ul class="modal-product__tags">${y}</ul>
        <p class="modal-product__description">${i}</p>
        <p class="modal-product__shipping-information">Shipping: ${d}</p>
        <p class="modal-product__return-policy">Return Policy: ${a}</p>
        <p class="modal-product__price">Price: ${o} $</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`}function w(t){s.modalProduct.innerHTML="",s.modalProduct.insertAdjacentHTML("beforeend",C(t))}function M(t,e){e.querySelectorAll(".categories__btn").forEach(r=>r.classList.remove("categories__btn--active")),t.classList.add("categories__btn--active")}function S(){s.modal.classList.add("modal--is--open")}function k(){s.modal.classList.remove("modal--is--open")}async function q(t){const e=t.target.closest(".categories__btn");if(!e)return;M(e,s.categoryList);const o=e.textContent.trim();s.productList.innerHTML="",m();try{let r;o.toLowerCase()==="all"?r=await u(1):r=await f(o),r&&Array.isArray(r.products)&&r.products.length>0?l(r.products):p()}catch(r){c.error({message:r.message,position:"topRight"})}}async function A(t){const e=t.target.closest(".products__item");if(!e)return;const o=e.getAttribute("data-id");try{const r=await L(o);w(r),S();return}catch(r){c.error({message:r.message,position:"topRight"})}}async function R(t){t.preventDefault();const e=s.searchInput.value.trim();if(e){s.productList.innerHTML="",m();try{const o=await b(e);o.products.length>0?l(o.products):p()}catch(o){c.error({message:o.message,position:"topRight"})}}}async function B(){s.searchInput.value="",s.productList.innerHTML="",m();try{const t=await u(1);t&&Array.isArray(t.products)&&t.products.length>0?l(t.products):p()}catch(t){c.error({message:t.message,position:"topRight"})}}P();const T=1;v(T);s.categoryList.addEventListener("click",q);s.productList.addEventListener("click",A);s.modalCloseBtn.addEventListener("click",k);s.searchForm.addEventListener("submit",R);s.searchBtnClear.addEventListener("click",B);
//# sourceMappingURL=index.js.map
